spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
            client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            scope: profile, email

          github:
            client-id: ${{ secrets.GH_CLIENT_ID }}
            client-secret: ${{ secrets.GH_CLIENT_SECRET }}
            scope: name,email

          naver:
            client-id: ${{ secrets.NAVER_CLIENT_ID }}
            client-secret: ${{ secrets.NAVER_CLIENT_SECRET }}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email, nickname
            client-name: naver

          kakao:
            client-id: ${{ secrets.KAKAO_CLIENT_ID }}
            client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - kakao_account.name
              - kakao_account.email
            client-name: kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id